"use client";
import { useState } from "react";
import DocLayout from "../../../components/DocLayout";
import DocPageNav from "../../../components/DocPageNav";
import { CheckCircle, ExternalLink, AlertCircle } from "lucide-react";

const steps = [
  {
    number: "01",
    emoji: "🍴",
    title: "Fork the Repository",
    detail:
      "You must use YOUR OWN forked copy. The Deployer Bot reads from your fork — this is how it injects your variables and keeps your bot private.",
    actions: [
      {
        label: "Open CipherElite on GitHub",
        href: "https://github.com/rishabhops/CipherElite",
        icon: "🔗",
      },
    ],
    substeps: [
      "Go to https://github.com/rishabhops/CipherElite",
      "Click the Fork button in the top-right corner",
      "Wait for GitHub to create your fork",
      "Copy your fork URL (e.g. github.com/YOUR_USERNAME/CipherElite)",
    ],
    warning:
      "Critical: You must use YOUR forked link, not the original. Using the original repo link will fail.",
  },
  {
    number: "02",
    emoji: "🔑",
    title: "Generate Your ELITE_SESSION",
    detail:
      "The ELITE_SESSION is not a regular Telegram session string. It is generated by our official bot and is cryptographically bound to CipherElite. Do NOT generate it from any other source.",
    actions: [
      {
        label: "Open @elite_session_maker_bot on Telegram",
        href: "https://t.me/elite_session_maker_bot",
        icon: "📲",
      },
    ],
    substeps: [
      "Start @elite_session_maker_bot on Telegram",
      "Send /start and follow the prompts",
      "Enter your phone number when asked",
      "Enter the OTP sent to your Telegram account",
      "Copy the ELITE_SESSION string shown",
    ],
    warning:
      "Never share your ELITE_SESSION with anyone. It grants full access to your Telegram account.",
  },
  {
    number: "03",
    emoji: "🚀",
    title: "Deploy via @elitedeployerbot",
    detail:
      "The Deployer Bot will clone your forked repository, inject your environment variables, and start your bot on real servers — all in under 30 seconds.",
    actions: [
      {
        label: "Open @elitedeployerbot on Telegram",
        href: "https://t.me/elitedeployerbot",
        icon: "🤖",
      },
    ],
    substeps: [
      "Start @elitedeployerbot on Telegram",
      "The bot automatically verifies you and says: ✅ Verified! Send your FORKED GitHub URL.",
      "Paste your forked repository URL directly — no command needed!",
      "Bot asks for each variable one by one: API_ID → API_HASH → ELITE_SESSION → LOG_CHAT_ID → SUDO_USERS",
      "Enter each value when the bot asks — have all values ready before you start!",
      "Wait ~30 seconds — bot confirms deployment and sends you the live log link 🎉",
    ],
    tip: "No /deploy command needed! The bot guides you automatically. Just have all your variables copied and ready before you start.",
  },
];

export default function TelegramDeployPage() {
  const [completedSteps, setCompletedSteps] = useState([]);

  const toggleStep = (i) => {
    setCompletedSteps((prev) =>
      prev.includes(i) ? prev.filter((s) => s !== i) : [...prev, i],
    );
  };

  return (
    <DocLayout currentId="telegram-deploy">
      <div className="mb-10">
        <div
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold mb-4 border"
          style={{
            background: "rgba(241,0,112,0.1)",
            borderColor: "rgba(241,0,112,0.3)",
            color: "#F77247",
          }}
        >
          📲 Telegram Deploy
        </div>
        <h1 className="text-4xl sm:text-5xl font-black text-white mb-4 leading-tight">
          Deploy via{" "}
          <span
            style={{
              background: "linear-gradient(135deg, #F10070, #F77247)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              backgroundClip: "text",
            }}
          >
            Telegram Bot
          </span>
        </h1>
        <p className="text-gray-400 text-lg leading-relaxed max-w-2xl">
          The easiest and recommended way. Free 24/7 hosting. No VPS. No credit
          card. Complete in under 30 seconds.
        </p>
      </div>

      <div className="h-px bg-gradient-to-r from-[#F10070]/30 via-[#F10070]/10 to-transparent mb-10" />

      {/* Benefits banner */}
      <div
        className="p-5 rounded-2xl border mb-10 grid sm:grid-cols-3 gap-4"
        style={{
          background: "rgba(16,185,129,0.05)",
          borderColor: "rgba(16,185,129,0.2)",
        }}
      >
        {[
          {
            icon: "☁️",
            title: "Real Server Hosting",
            desc: "Your bot runs on actual servers, 24/7.",
          },
          {
            icon: "📡",
            title: "Live Log Streaming",
            desc: "See your bot's logs directly in Telegram.",
          },
          {
            icon: "⚡",
            title: "Instant Variable Edit",
            desc: "Change env vars without re-deploying.",
          },
        ].map((b, i) => (
          <div key={i} className="flex items-start gap-3">
            <span className="text-xl mt-0.5">{b.icon}</span>
            <div>
              <p className="text-sm font-bold text-white">{b.title}</p>
              <p className="text-xs text-gray-400">{b.desc}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Video tutorial */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold text-white mb-5 flex items-center gap-3">
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center text-sm"
            style={{ background: "rgba(241,0,112,0.15)", color: "#F10070" }}
          >
            🎥
          </span>
          Video Tutorial
        </h2>
        <a
          href="https://www.youtube.com/watch?v=XBHyZyJcv5c"
          target="_blank"
          rel="noopener noreferrer"
          className="block relative rounded-2xl overflow-hidden border border-[#1e1e2e] group"
        >
          <img
            src="https://img.youtube.com/vi/XBHyZyJcv5c/maxresdefault.jpg"
            alt="CipherElite Tutorial"
            className="w-full aspect-video object-cover group-hover:scale-105 transition-transform duration-300"
          />
          <div
            className="absolute inset-0 flex items-center justify-center"
            style={{ background: "rgba(0,0,0,0.45)" }}
          >
            <div
              className="w-16 h-16 rounded-full flex items-center justify-center group-hover:scale-110 transition-transform shadow-2xl"
              style={{
                background: "linear-gradient(135deg, #F10070, #F77247)",
              }}
            >
              <span className="text-white text-2xl ml-1">▶</span>
            </div>
          </div>
          <div className="absolute bottom-4 left-4 right-4">
            <div
              className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-bold"
              style={{
                background: "rgba(0,0,0,0.7)",
                color: "#F77247",
                border: "1px solid rgba(241,0,112,0.3)",
              }}
            >
              ▶️ Watch: Deploy CipherElite in 60 Seconds (Free)
            </div>
          </div>
        </a>
      </section>

      {/* Step-by-step */}
      <section className="mb-12">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-2xl font-bold text-white">Step-by-Step Guide</h2>
          <div className="text-xs text-gray-500 font-medium">
            {completedSteps.length}/{steps.length} completed
          </div>
        </div>

        {/* Progress bar */}
        <div className="h-1.5 rounded-full bg-[#1e1e2e] mb-8 overflow-hidden">
          <div
            className="h-full rounded-full transition-all duration-500"
            style={{
              width: `${(completedSteps.length / steps.length) * 100}%`,
              background: "linear-gradient(90deg, #F10070, #F77247)",
            }}
          />
        </div>

        <div className="space-y-6">
          {steps.map((step, i) => {
            const done = completedSteps.includes(i);
            return (
              <div
                key={i}
                className="rounded-2xl border transition-all duration-200"
                style={{
                  borderColor: done
                    ? "rgba(16,185,129,0.4)"
                    : "rgba(30,30,46,1)",
                  background: done ? "rgba(16,185,129,0.04)" : "#0d0d14",
                }}
              >
                {/* Step header */}
                <div className="p-5 flex items-start gap-4">
                  <div
                    className="w-12 h-12 rounded-xl flex items-center justify-center text-2xl shrink-0 transition-all"
                    style={{
                      background: done
                        ? "rgba(16,185,129,0.15)"
                        : "rgba(241,0,112,0.1)",
                    }}
                  >
                    {done ? "✅" : step.emoji}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 flex-wrap mb-1">
                      <span className="text-xs font-black text-gray-600 font-mono">
                        {step.number}
                      </span>
                      <h3 className="font-bold text-white text-base">
                        {step.title}
                      </h3>
                    </div>
                    <p className="text-gray-400 text-sm leading-relaxed mb-4">
                      {step.detail}
                    </p>

                    {/* Substeps */}
                    <div className="space-y-2 mb-4">
                      {step.substeps.map((sub, si) => (
                        <div key={si} className="flex items-start gap-2.5">
                          <div
                            className="w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold shrink-0 mt-0.5"
                            style={{
                              background: "rgba(241,0,112,0.15)",
                              color: "#F10070",
                            }}
                          >
                            {si + 1}
                          </div>
                          <span className="text-sm text-gray-300">{sub}</span>
                        </div>
                      ))}
                    </div>

                    {/* Warning or Tip */}
                    {step.warning && (
                      <div
                        className="flex items-start gap-2.5 p-3 rounded-xl mb-4"
                        style={{
                          background: "rgba(239,68,68,0.08)",
                          border: "1px solid rgba(239,68,68,0.2)",
                        }}
                      >
                        <AlertCircle
                          size={14}
                          className="text-red-400 shrink-0 mt-0.5"
                        />
                        <p className="text-xs text-red-300 leading-relaxed">
                          {step.warning}
                        </p>
                      </div>
                    )}
                    {step.tip && (
                      <div
                        className="flex items-start gap-2.5 p-3 rounded-xl mb-4"
                        style={{
                          background: "rgba(241,0,112,0.05)",
                          border: "1px solid rgba(241,0,112,0.15)",
                        }}
                      >
                        <span className="text-sm shrink-0">💡</span>
                        <p className="text-xs text-gray-300 leading-relaxed">
                          {step.tip}
                        </p>
                      </div>
                    )}

                    {/* Action buttons */}
                    <div className="flex flex-wrap gap-2">
                      {step.actions.map((action, ai) => (
                        <a
                          key={ai}
                          href={action.href}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-semibold text-white transition-all hover:scale-105"
                          style={{
                            background:
                              "linear-gradient(135deg, #F10070, #F77247)",
                          }}
                        >
                          <span>{action.icon}</span>
                          {action.label}
                          <ExternalLink size={12} />
                        </a>
                      ))}
                      <button
                        onClick={() => toggleStep(i)}
                        className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-semibold transition-all border"
                        style={{
                          borderColor: done
                            ? "rgba(16,185,129,0.4)"
                            : "rgba(30,30,46,1)",
                          color: done ? "#10b981" : "#6b7280",
                          background: done
                            ? "rgba(16,185,129,0.08)"
                            : "transparent",
                        }}
                      >
                        <CheckCircle size={14} />
                        {done ? "Completed" : "Mark done"}
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* Success message */}
      {completedSteps.length === steps.length && (
        <div
          className="p-6 rounded-2xl border text-center mb-10"
          style={{
            background: "rgba(16,185,129,0.08)",
            borderColor: "rgba(16,185,129,0.3)",
          }}
        >
          <div className="text-4xl mb-3">🎉</div>
          <h3 className="text-white font-bold text-lg mb-2">
            CipherElite is Live!
          </h3>
          <p className="text-gray-400 text-sm">
            Your bot should now be running 24/7. Check your Telegram for the
            live log link.
          </p>
        </div>
      )}

      {/* Why Telegram Deploy */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold text-white mb-5">
          Why Use This Method?
        </h2>
        <div className="grid sm:grid-cols-2 gap-4">
          {[
            {
              pro: "✅ No VPS required",
              desc: "Your bot runs on our infrastructure for free.",
            },
            {
              pro: "✅ No credit card",
              desc: "Truly free. No payment method needed at any step.",
            },
            {
              pro: "✅ Live logs in Telegram",
              desc: "Monitor your bot without opening a server terminal.",
            },
            {
              pro: "✅ Instant variable editing",
              desc: "Change API keys or settings without re-deploying.",
            },
            {
              pro: "✅ One-command restart",
              desc: "Restart your bot instantly from Telegram.",
            },
            {
              pro: "✅ Beginner friendly",
              desc: "No command line knowledge required whatsoever.",
            },
          ].map((item, i) => (
            <div
              key={i}
              className="flex items-start gap-3 p-4 rounded-xl border border-[#1e1e2e] bg-[#0d0d14]"
            >
              <span className="text-sm font-bold text-[#10b981] shrink-0 mt-0.5">
                {item.pro}
              </span>
              <span className="text-xs text-gray-400 leading-relaxed">
                {item.desc}
              </span>
            </div>
          ))}
        </div>
      </section>

      <DocPageNav currentId="telegram-deploy" />
    </DocLayout>
  );
}
